using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.AspNetCore.Http;
using SecureJournal.Core.Application;
using SecureJournal.Core.Domain;
using SecureJournal.Core.Security;
using SecureJournal.Web.Services;
using Xunit;

namespace SecureJournal.Tests;

public sealed class InMemorySecureJournalAppServiceTests
{
    [Fact]
    public void BootstrapState_StartsUnauthenticated_AndAdminCanLogin()
    {
        using var ctx = TestAppContext.Create();

        Assert.False(ctx.App.HasCurrentUser());
        Assert.Throws<UnauthorizedAccessException>(() => ctx.App.GetCurrentUser());

        var users = ctx.App.GetAvailableUsers();
        Assert.Single(users);
        Assert.Equal("admin", users[0].Username);

        Assert.True(ctx.App.TryLocalLogin("admin", "AdminPass123!").Success);
        Assert.True(ctx.App.HasCurrentUser());

        var current = ctx.App.GetCurrentUser();
        Assert.Equal("admin", current.Username);
        Assert.Equal(AppRole.Administrator, current.Role);

        var dashboard = ctx.App.GetDashboardSummary();
        Assert.Equal(1, dashboard.Users);
        Assert.Equal(0, dashboard.TotalProjects);
        Assert.Equal(0, dashboard.Groups);
        Assert.True(dashboard.AuditEventsVisible >= 1);
    }

    [Fact]
    public void AdminCanCreateUsersProjectsGroupsAndAssignments_AndProjectUserGetsAccess()
    {
        using var ctx = TestAppContext.Create();
        ctx.LoginAsAdmin();

        var project = ctx.App.CreateProject(new CreateProjectRequest
        {
            Code = "PRJ1",
            Name = "Project One",
            Description = "Test project"
        });

        var group = ctx.App.CreateGroup(new CreateGroupRequest
        {
            Name = "Ops Team"
        });

        var projectUser = ctx.App.CreateUser(new CreateUserRequest
        {
            Username = "alice",
            DisplayName = "Alice Project",
            Role = AppRole.ProjectUser,
            IsLocalAccount = true,
            LocalPassword = "AlicePass123!"
        });

        Assert.True(ctx.App.AssignUserToGroup(new AssignUserToGroupRequest
        {
            UserId = projectUser.UserId,
            GroupId = group.GroupId
        }));
        Assert.False(ctx.App.AssignUserToGroup(new AssignUserToGroupRequest
        {
            UserId = projectUser.UserId,
            GroupId = group.GroupId
        }));

        Assert.True(ctx.App.AssignGroupToProject(new AssignGroupToProjectRequest
        {
            GroupId = group.GroupId,
            ProjectId = project.ProjectId
        }));
        Assert.False(ctx.App.AssignGroupToProject(new AssignGroupToProjectRequest
        {
            GroupId = group.GroupId,
            ProjectId = project.ProjectId
        }));

        var adminUsers = ctx.App.GetUsers();
        Assert.Contains(adminUsers, u => u.Username == "alice" && u.Groups.Contains("Ops Team"));

        var adminGroups = ctx.App.GetGroups();
        Assert.Contains(adminGroups, g => g.Name == "Ops Team" && g.Members.Contains("Alice Project") && g.ProjectCodes.Contains("PRJ1"));

        var adminProjects = ctx.App.GetProjects();
        Assert.Contains(adminProjects, p => p.ProjectId == project.ProjectId && p.AssignedGroups.Contains("Ops Team"));

        var login = ctx.App.TryLocalLogin("alice", "AlicePass123!");
        Assert.True(login.Success);
        Assert.Equal("alice", ctx.App.GetCurrentUser().Username);

        var projectUserProjects = ctx.App.GetProjects();
        Assert.Single(projectUserProjects);
        Assert.Equal("PRJ1", projectUserProjects[0].Code);
        Assert.True(projectUserProjects[0].HasAccessForCurrentUser);

        Assert.Empty(ctx.App.GetUsers());
        Assert.Empty(ctx.App.GetGroups());

        var allUsers = ctx.App.GetAvailableUsers();
        Assert.Equal(2, allUsers.Count);

        ctx.App.SetCurrentUser(allUsers.Single(u => u.Username == "admin").UserId);
        Assert.Equal("admin", ctx.App.GetCurrentUser().Username);

        var dashboard = ctx.App.GetDashboardSummary();
        Assert.Equal(2, dashboard.Users);
        Assert.Equal(1, dashboard.TotalProjects);
        Assert.Equal(1, dashboard.Groups);
    }

    [Fact]
    public void ProjectCode_IsAutoGenerated_WhenNotProvided()
    {
        using var ctx = TestAppContext.Create();
        ctx.LoginAsAdmin();

        var p1 = ctx.App.CreateProject(new CreateProjectRequest
        {
            Name = "Auto One",
            Description = "No code provided"
        });
        var p2 = ctx.App.CreateProject(new CreateProjectRequest
        {
            Name = "Auto Two",
            Description = "No code provided"
        });

        Assert.Equal("PRJ0001", p1.Code);
        Assert.Equal("PRJ0002", p2.Code);
        Assert.NotEqual(p1.Code, p2.Code);
    }

    [Fact]
    public void SeparateServiceScopes_KeepIndependentCurrentUsers()
    {
        var repoRoot = FindRepoRoot(AppContext.BaseDirectory);
        var dbPath = Path.Combine(repoRoot, ".artifacts", "tests", $"securejournal-session-{Guid.NewGuid():N}.db");
        Directory.CreateDirectory(Path.GetDirectoryName(dbPath)!);

        try
        {
            var configuration = new ConfigurationBuilder()
                .AddInMemoryCollection(new Dictionary<string, string?>
                {
                    ["ConnectionStrings:SecureJournalSqlite"] = $"Data Source={dbPath}",
                    ["Security:JournalEncryptionKey"] = "tests-journal-key",
                    ["Security:LocalPasswordMinLength"] = "8",
                    ["BootstrapAdmin:Username"] = "admin",
                    ["BootstrapAdmin:DisplayName"] = "Startup Admin",
                    ["BootstrapAdmin:Password"] = "AdminPass123!"
                })
                .Build();

            var shared = new PrototypeSharedState();
            var sqlite = new SqlitePrototypeStore(configuration);
            var checksum = new Sha256ChecksumService();
            var journalEncryptor = new JournalFieldEncryptor(EncryptionKeyParser.GetKeyBytes(configuration["Security:JournalEncryptionKey"], "journal"));
            var auditEncryptor = new PlaintextAuditFieldEncryptor();
            var logger = NullLogger<InMemorySecureJournalAppService>.Instance;

            var appA = new InMemorySecureJournalAppService(checksum, journalEncryptor, auditEncryptor, sqlite, shared, configuration, logger);
            var appB = new InMemorySecureJournalAppService(checksum, journalEncryptor, auditEncryptor, sqlite, shared, configuration, logger);

            Assert.False(appA.HasCurrentUser());
            Assert.False(appB.HasCurrentUser());

            Assert.True(appA.TryLocalLogin("admin", "AdminPass123!").Success);
            Assert.True(appA.HasCurrentUser());
            Assert.False(appB.HasCurrentUser());

            var bob = appA.CreateUser(new CreateUserRequest
            {
                Username = "bobscope",
                DisplayName = "Bob Scope",
                Role = AppRole.ProjectUser,
                IsLocalAccount = true,
                LocalPassword = "BobScope123!"
            });

            Assert.True(appB.TryLocalLogin("bobscope", "BobScope123!").Success);
            Assert.Equal("admin", appA.GetCurrentUser().Username);
            Assert.Equal(bob.Username, appB.GetCurrentUser().Username);
        }
        finally
        {
            try
            {
                if (File.Exists(dbPath))
                {
                    File.Delete(dbPath);
                }
            }
            catch
            {
                // ignore cleanup failure in test
            }
        }
    }

    [Fact]
    public void SessionCookieToken_RestoresScopedUser_AndExpiredTokenIsRejected()
    {
        var repoRoot = FindRepoRoot(AppContext.BaseDirectory);
        var dbPath = Path.Combine(repoRoot, ".artifacts", "tests", $"securejournal-cookie-{Guid.NewGuid():N}.db");
        Directory.CreateDirectory(Path.GetDirectoryName(dbPath)!);

        try
        {
            var configuration = new ConfigurationBuilder()
                .AddInMemoryCollection(new Dictionary<string, string?>
                {
                    ["ConnectionStrings:SecureJournalSqlite"] = $"Data Source={dbPath}",
                    ["Security:JournalEncryptionKey"] = "tests-journal-key",
                    ["Security:LocalPasswordMinLength"] = "8",
                    ["Security:SessionCookieName"] = "SecureJournal.Session",
                    ["Security:SessionCookieHours"] = "8",
                    ["BootstrapAdmin:Username"] = "admin",
                    ["BootstrapAdmin:DisplayName"] = "Startup Admin",
                    ["BootstrapAdmin:Password"] = "AdminPass123!"
                })
                .Build();

            var shared = new PrototypeSharedState();
            var sqlite = new SqlitePrototypeStore(configuration);
            var checksum = new Sha256ChecksumService();
            var journalEncryptor = new JournalFieldEncryptor(EncryptionKeyParser.GetKeyBytes(configuration["Security:JournalEncryptionKey"], "journal"));
            var auditEncryptor = new PlaintextAuditFieldEncryptor();
            var logger = NullLogger<InMemorySecureJournalAppService>.Instance;
            var sessions = new PrototypeSessionRegistry();

            var loginService = new InMemorySecureJournalAppService(
                checksum,
                journalEncryptor,
                auditEncryptor,
                sqlite,
                shared,
                configuration,
                logger);

            Assert.True(loginService.TryLocalLogin("admin", "AdminPass123!").Success);
            var adminId = loginService.GetCurrentUser().UserId;

            var validToken = sessions.CreateSession(adminId, TimeSpan.FromHours(8));
            var expiredToken = sessions.CreateSession(adminId, TimeSpan.FromSeconds(-1));

            var accessorValid = new HttpContextAccessor { HttpContext = new DefaultHttpContext() };
            accessorValid.HttpContext.Request.Headers.Cookie = $"SecureJournal.Session={validToken}";

            var restoredService = new InMemorySecureJournalAppService(
                checksum,
                journalEncryptor,
                auditEncryptor,
                sqlite,
                shared,
                configuration,
                logger,
                accessorValid,
                sessions);

            Assert.True(restoredService.HasCurrentUser());
            Assert.Equal("admin", restoredService.GetCurrentUser().Username);

            var accessorExpired = new HttpContextAccessor { HttpContext = new DefaultHttpContext() };
            accessorExpired.HttpContext.Request.Headers.Cookie = $"SecureJournal.Session={expiredToken}";

            var expiredService = new InMemorySecureJournalAppService(
                checksum,
                journalEncryptor,
                auditEncryptor,
                sqlite,
                shared,
                configuration,
                logger,
                accessorExpired,
                sessions);

            Assert.False(expiredService.HasCurrentUser());
        }
        finally
        {
            try
            {
                if (File.Exists(dbPath))
                {
                    File.Delete(dbPath);
                }
            }
            catch
            {
                // ignore cleanup failure in test
            }
        }
    }

    [Fact]
    public void LocalPasswordChange_RequiresCurrentPassword_AndUpdatesLogin()
    {
        using var ctx = TestAppContext.Create();
        ctx.LoginAsAdmin();

        var user = ctx.App.CreateUser(new CreateUserRequest
        {
            Username = "bob",
            DisplayName = "Bob User",
            Role = AppRole.ProjectUser,
            IsLocalAccount = true,
            LocalPassword = "OldPass123!"
        });

        var login = ctx.App.TryLocalLogin(user.Username, "OldPass123!");
        Assert.True(login.Success);

        var wrongCurrent = ctx.App.ChangeCurrentUserPassword(new ChangePasswordRequest
        {
            CurrentPassword = "wrong",
            NewPassword = "NewPass123!"
        });
        Assert.False(wrongCurrent.Success);

        var samePassword = ctx.App.ChangeCurrentUserPassword(new ChangePasswordRequest
        {
            CurrentPassword = "OldPass123!",
            NewPassword = "OldPass123!"
        });
        Assert.False(samePassword.Success);

        var changed = ctx.App.ChangeCurrentUserPassword(new ChangePasswordRequest
        {
            CurrentPassword = "OldPass123!",
            NewPassword = "NewPass123!"
        });
        Assert.True(changed.Success);

        ctx.App.TryLocalLogin("admin", "AdminPass123!");

        var oldLogin = ctx.App.TryLocalLogin("bob", "OldPass123!");
        Assert.False(oldLogin.Success);

        var newLogin = ctx.App.TryLocalLogin("bob", "NewPass123!");
        Assert.True(newLogin.Success);
    }

    [Fact]
    public void JournalLifecycle_AccessControlAndSoftDelete_Work()
    {
        using var ctx = TestAppContext.Create();
        ctx.LoginAsAdmin();
        var setup = ctx.CreateProjectUserWithAccess("charlie", "Charlie User", "PRJ2", "Project Two", "Team Charlie", "CharliePass123!");
        var auditor = ctx.App.CreateUser(new CreateUserRequest
        {
            Username = "auditor1",
            DisplayName = "Auditor One",
            Role = AppRole.Auditor,
            IsLocalAccount = true,
            LocalPassword = "AuditPass123!"
        });

        Assert.True(ctx.App.TryLocalLogin("charlie", "CharliePass123!").Success);

        var entry = ctx.App.CreateJournalEntry(new CreateJournalEntryRequest
        {
            ProjectId = setup.Project.ProjectId,
            Action = "Incident",
            Subject = "Subsystem restart",
            Description = "Service restarted after configuration update.",
            Notes = "Observed during maintenance window."
        });

        var visibleToProjectUser = ctx.App.GetJournalEntries(setup.Project.ProjectId);
        Assert.Single(visibleToProjectUser);
        Assert.Equal(entry.RecordId, visibleToProjectUser[0].RecordId);

        Assert.False(ctx.App.SoftDeleteJournalEntry(Guid.NewGuid()));
        Assert.True(ctx.App.SoftDeleteJournalEntry(entry.RecordId, "Cleanup duplicate"));
        Assert.False(ctx.App.SoftDeleteJournalEntry(entry.RecordId, "Again"));

        Assert.Empty(ctx.App.GetJournalEntries(setup.Project.ProjectId));
        Assert.Empty(ctx.App.GetJournalEntries(setup.Project.ProjectId, includeSoftDeleted: true));

        Assert.True(ctx.App.TryLocalLogin("admin", "AdminPass123!").Success);
        var adminVisible = ctx.App.GetJournalEntries(setup.Project.ProjectId, includeSoftDeleted: true);
        Assert.Single(adminVisible);
        Assert.True(adminVisible[0].IsSoftDeleted);
        Assert.Equal("Cleanup duplicate", adminVisible[0].DeleteReason);

        Assert.True(ctx.App.TryLocalLogin("auditor1", "AuditPass123!").Success);
        Assert.Throws<UnauthorizedAccessException>(() => ctx.App.GetJournalEntries(setup.Project.ProjectId));
        Assert.Throws<UnauthorizedAccessException>(() => ctx.App.CreateJournalEntry(new CreateJournalEntryRequest
        {
            ProjectId = setup.Project.ProjectId,
            Action = "Test",
            Subject = "Denied",
            Description = "Auditor should not create journal entries"
        }));
    }

    [Fact]
    public void AuditSearchAndExports_RespectRoles()
    {
        using var ctx = TestAppContext.Create();
        ctx.LoginAsAdmin();
        var setup = ctx.CreateProjectUserWithAccess("dana", "Dana User", "PRJ3", "Project Three", "Team Dana", "DanaPass123!");
        var auditor = ctx.App.CreateUser(new CreateUserRequest
        {
            Username = "auditor2",
            DisplayName = "Auditor Two",
            Role = AppRole.Auditor,
            IsLocalAccount = true,
            LocalPassword = "AuditPass456!"
        });

        Assert.True(ctx.App.TryLocalLogin("dana", "DanaPass123!").Success);
        var created = ctx.App.CreateJournalEntry(new CreateJournalEntryRequest
        {
            ProjectId = setup.Project.ProjectId,
            Action = "Maintenance",
            Subject = "Patch install",
            Description = "Patched the environment.",
            Notes = ""
        });

        Assert.Throws<UnauthorizedAccessException>(() => ctx.App.SearchAuditLogs(new AuditSearchFilter()));
        Assert.Throws<UnauthorizedAccessException>(() => ctx.App.ExportAuditLogs(new AuditExportRequest { Format = ExportFormat.Json }));
        Assert.Throws<UnauthorizedAccessException>(() => ctx.App.ExportJournalEntries(new JournalExportRequest { Format = ExportFormat.Json }));
        Assert.Throws<UnauthorizedAccessException>(() => ctx.App.ValidateAuditLogChecksum(Guid.NewGuid()));

        Assert.True(ctx.App.TryLocalLogin("admin", "AdminPass123!").Success);

        var auditRows = ctx.App.SearchAuditLogs(new AuditSearchFilter
        {
            ProjectId = setup.Project.ProjectId
        });
        Assert.NotEmpty(auditRows);
        Assert.Contains(auditRows, a => a.ProjectId == setup.Project.ProjectId);
        Assert.Contains(auditRows, a => a.RelatedJournalEntry is not null && a.RelatedJournalEntry.Subject == "Patch install");
        var validatedByAdmin = ctx.App.ValidateAuditLogChecksum(auditRows[0].AuditId);
        Assert.True(validatedByAdmin.IsValid);

        var journalExport = ctx.App.ExportJournalEntries(new JournalExportRequest
        {
            Format = ExportFormat.Csv,
            Filter = new JournalExportFilter
            {
                ProjectId = setup.Project.ProjectId,
                IncludeSoftDeleted = true
            }
        });
        Assert.Equal("text/csv", journalExport.ContentType);
        Assert.True(journalExport.RowCount >= 1);
        Assert.Contains("Patch install", journalExport.ContentText);

        Assert.True(ctx.App.TryLocalLogin("auditor2", "AuditPass456!").Success);
        var auditExport = ctx.App.ExportAuditLogs(new AuditExportRequest
        {
            Format = ExportFormat.Json,
            Filter = new AuditSearchFilter
            {
                ProjectId = setup.Project.ProjectId
            }
        });
        Assert.Equal("application/json", auditExport.ContentType);
        Assert.True(auditExport.RowCount >= 1);
        Assert.Contains("rows", auditExport.ContentText, StringComparison.OrdinalIgnoreCase);

        var auditRowsForAuditor = ctx.App.SearchAuditLogs(new AuditSearchFilter
        {
            ProjectId = setup.Project.ProjectId
        });
        var validatedByAuditor = ctx.App.ValidateAuditLogChecksum(auditRowsForAuditor[0].AuditId);
        Assert.True(validatedByAuditor.IsValid);
    }

    [Fact]
    public void StatePersistsAcrossServiceInstances()
    {
        using var ctx = TestAppContext.Create();
        ctx.LoginAsAdmin();
        var setup = ctx.CreateProjectUserWithAccess("erin", "Erin User", "PRJ4", "Project Four", "Team Erin", "ErinPass123!");

        Assert.True(ctx.App.TryLocalLogin("erin", "ErinPass123!").Success);
        var entry = ctx.App.CreateJournalEntry(new CreateJournalEntryRequest
        {
            ProjectId = setup.Project.ProjectId,
            Action = "Ops",
            Subject = "Persistence check",
            Description = "Entry should persist across service instances.",
        });

        var dbPath = ctx.DatabasePath;
        ctx.Dispose();

        using var ctx2 = TestAppContext.Create(existingDatabasePath: dbPath, deleteOnDispose: true);
        Assert.True(ctx2.App.TryLocalLogin("erin", "ErinPass123!").Success);

        var projects = ctx2.App.GetProjects();
        Assert.Contains(projects, p => p.Code == "PRJ4");

        var entries = ctx2.App.GetJournalEntries(setup.Project.ProjectId);
        Assert.Contains(entries, e => e.RecordId == entry.RecordId);

        Assert.True(ctx2.App.TryLocalLogin("admin", "AdminPass123!").Success);
        var groups = ctx2.App.GetGroups();
        Assert.Contains(groups, g => g.Name == "Team Erin" && g.ProjectCodes.Contains("PRJ4"));
    }

    [Fact]
    public void LogoutAndAdminPasswordReset_WithPasswordPolicy_Work()
    {
        using var ctx = TestAppContext.Create();
        ctx.LoginAsAdmin();

        var created = ctx.App.CreateUser(new CreateUserRequest
        {
            Username = "frank",
            DisplayName = "Frank User",
            Role = AppRole.ProjectUser,
            IsLocalAccount = true,
            LocalPassword = "FrankPass123!"
        });

        var weakCreate = Assert.Throws<InvalidOperationException>(() => ctx.App.CreateUser(new CreateUserRequest
        {
            Username = "weakuser",
            DisplayName = "Weak User",
            Role = AppRole.ProjectUser,
            IsLocalAccount = true,
            LocalPassword = "short"
        }));
        Assert.Contains("at least", weakCreate.Message, StringComparison.OrdinalIgnoreCase);

        var noSpecialCreate = Assert.Throws<InvalidOperationException>(() => ctx.App.CreateUser(new CreateUserRequest
        {
            Username = "nospecial",
            DisplayName = "No Special",
            Role = AppRole.ProjectUser,
            IsLocalAccount = true,
            LocalPassword = "NoSpecial123"
        }));
        Assert.Contains("special character", noSpecialCreate.Message, StringComparison.OrdinalIgnoreCase);

        var weakReset = Assert.Throws<InvalidOperationException>(() => ctx.App.ResetLocalUserPassword(new AdminResetPasswordRequest
        {
            UserId = created.UserId,
            NewPassword = "short"
        }));
        Assert.Contains("at least", weakReset.Message, StringComparison.OrdinalIgnoreCase);

        var reset = ctx.App.ResetLocalUserPassword(new AdminResetPasswordRequest
        {
            UserId = created.UserId,
            NewPassword = "ResetPass123!"
        });
        Assert.True(reset.Success);

        ctx.App.LogoutCurrentUser();
        Assert.False(ctx.App.HasCurrentUser());
        Assert.Throws<UnauthorizedAccessException>(() => ctx.App.GetDashboardSummary());

        Assert.False(ctx.App.TryLocalLogin("frank", "FrankPass123!").Success);
        Assert.True(ctx.App.TryLocalLogin("frank", "ResetPass123!").Success);

        var weakChange = ctx.App.ChangeCurrentUserPassword(new ChangePasswordRequest
        {
            CurrentPassword = "ResetPass123!",
            NewPassword = "tiny"
        });
        Assert.False(weakChange.Success);
        Assert.Contains("at least", weakChange.Message, StringComparison.OrdinalIgnoreCase);

        var noDigitChange = ctx.App.ChangeCurrentUserPassword(new ChangePasswordRequest
        {
            CurrentPassword = "ResetPass123!",
            NewPassword = "NoDigitPass!"
        });
        Assert.False(noDigitChange.Success);
        Assert.Contains("digit", noDigitChange.Message, StringComparison.OrdinalIgnoreCase);
    }

    private sealed class TestAppContext : IDisposable
    {
        private bool _disposed;

        private TestAppContext(
            ISecureJournalAppService app,
            string databasePath,
            bool deleteOnDispose)
        {
            App = app;
            DatabasePath = databasePath;
            DeleteOnDispose = deleteOnDispose;
        }

        public ISecureJournalAppService App { get; }
        public string DatabasePath { get; }
        public bool DeleteOnDispose { get; }

        public static TestAppContext Create(string? existingDatabasePath = null, bool deleteOnDispose = true)
        {
            var databasePath = existingDatabasePath ?? BuildUniqueDatabasePath();
            Directory.CreateDirectory(Path.GetDirectoryName(databasePath)!);

            var configuration = new ConfigurationBuilder()
                .AddInMemoryCollection(new Dictionary<string, string?>
                {
                    ["ConnectionStrings:SecureJournalSqlite"] = $"Data Source={databasePath}",
                    ["Security:JournalEncryptionKey"] = "tests-journal-key",
                    ["Security:LocalPasswordMinLength"] = "8",
                    ["BootstrapAdmin:Username"] = "admin",
                    ["BootstrapAdmin:DisplayName"] = "Startup Admin",
                    ["BootstrapAdmin:Password"] = "AdminPass123!"
                })
                .Build();

            var service = new InMemorySecureJournalAppService(
                new Sha256ChecksumService(),
                new JournalFieldEncryptor(EncryptionKeyParser.GetKeyBytes(configuration["Security:JournalEncryptionKey"], "journal")),
                new PlaintextAuditFieldEncryptor(),
                new SqlitePrototypeStore(configuration),
                new PrototypeSharedState(),
                configuration,
                NullLogger<InMemorySecureJournalAppService>.Instance);

            return new TestAppContext(service, databasePath, deleteOnDispose);
        }

        public void LoginAsAdmin()
        {
            Assert.True(App.TryLocalLogin("admin", "AdminPass123!").Success);
        }

        public (ProjectOverview Project, GroupOverview Group, UserOverview User) CreateProjectUserWithAccess(
            string username,
            string displayName,
            string projectCode,
            string projectName,
            string groupName,
            string password)
        {
            var project = App.CreateProject(new CreateProjectRequest
            {
                Code = projectCode,
                Name = projectName,
                Description = "Created from test helper"
            });
            var group = App.CreateGroup(new CreateGroupRequest
            {
                Name = groupName
            });
            var user = App.CreateUser(new CreateUserRequest
            {
                Username = username,
                DisplayName = displayName,
                Role = AppRole.ProjectUser,
                IsLocalAccount = true,
                LocalPassword = password
            });

            App.AssignUserToGroup(new AssignUserToGroupRequest
            {
                UserId = user.UserId,
                GroupId = group.GroupId
            });
            App.AssignGroupToProject(new AssignGroupToProjectRequest
            {
                GroupId = group.GroupId,
                ProjectId = project.ProjectId
            });

            return (project, group, user);
        }

        public void Dispose()
        {
            if (_disposed)
            {
                return;
            }

            _disposed = true;

            if (!DeleteOnDispose)
            {
                return;
            }

            try
            {
                if (File.Exists(DatabasePath))
                {
                    File.Delete(DatabasePath);
                }
            }
            catch
            {
                // Leave the file behind if cleanup fails to avoid masking test failures.
            }
        }

        private static string BuildUniqueDatabasePath()
        {
            var repoRoot = FindRepoRoot(AppContext.BaseDirectory);
            return Path.Combine(repoRoot, ".artifacts", "tests", $"securejournal-test-{Guid.NewGuid():N}.db");
        }

        private static string FindRepoRoot(string startDirectory)
        {
            var directory = new DirectoryInfo(startDirectory);
            while (directory is not null)
            {
                if (File.Exists(Path.Combine(directory.FullName, "SecureJournal.slnx")))
                {
                    return directory.FullName;
                }

                directory = directory.Parent;
            }

            throw new InvalidOperationException("Could not locate repository root.");
        }
    }

    private static string FindRepoRoot(string startDirectory)
    {
        var directory = new DirectoryInfo(startDirectory);
        while (directory is not null)
        {
            if (File.Exists(Path.Combine(directory.FullName, "SecureJournal.slnx")))
            {
                return directory.FullName;
            }

            directory = directory.Parent;
        }

        throw new InvalidOperationException("Could not locate repository root.");
    }
}
